// Generated by nifty from tests/scripts/blocks.nifty. Do not edit.
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <pthread.h>

static void *t_main(void *ni_arg) {
  (void)ni_arg;
  int64_t v_total = 0LL;
  {
    int64_t v_t = 2LL;
    v_t = (v_t + 3LL);
    v_total = (v_total + v_t);
  }
  {
    int64_t v_t = 10LL;
    v_t = (v_t + 1LL);
    v_total = (v_total + v_t);
  }
  {
    int64_t ni_e0 = v_total;
    printf("%lld\n", (long long)(ni_e0));
  }
  return NULL;
}

int main(void) {
  pthread_t ni_threads[1];
  if (pthread_create(&ni_threads[0], NULL, t_main, NULL) != 0) { fprintf(stderr, "nifty: failed to start thread main\n"); return 1; }
  pthread_join(ni_threads[0], NULL);
  return 0;
}
