// Generated by nifty from tests/scripts/hardware.nifty. Do not edit.
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <pthread.h>

// The one float -> int conversion: saturating, NaN-safe (NaN -> 0).
// A bare C cast of an out-of-range or NaN value is undefined behavior,
// so nifty never emits one.
static inline int64_t ni_ftoi(double f) {
  if (f != f) return 0;
  if (f >= 9223372036854775807.0) return INT64_MAX;
  if (f <= -9223372036854775808.0) return INT64_MIN;
  return (int64_t)f;
}

typedef struct {
  uint8_t m_r;
  uint8_t m_g;
  uint8_t m_b;
  uint8_t m_a;
} S_Pixel;

static void *t_main(void *ni_arg) {
  (void)ni_arg;
  uint8_t v_small[4] = {0};
  v_small[0LL] = 200LL;
  v_small[1LL] = 255LL;
  int64_t v_total = 0LL;
  {
    int64_t v_i = 0LL;
    const int64_t ni_end0 = 4LL;
    for (; v_i < ni_end0; ++v_i) {
      v_total = ((int64_t)v_total + (int64_t)v_small[v_i]);
    }
  }
  {
    int64_t ni_e1 = v_total;
    printf("%lld\n", (long long)(ni_e1));
  }
  S_Pixel v_p = {0};
  v_p.m_r = 255LL;
  v_p.m_g = 128LL;
  {
    int64_t ni_e2 = ((int64_t)v_p.m_r + (int64_t)v_p.m_g);
    printf("%lld\n", (long long)(ni_e2));
  }
  uint8_t v_c = 65LL;
  {
    int64_t ni_e3 = v_c;
    printf("%lld\n", (long long)(ni_e3));
  }
  int32_t v_big = 2000000000LL;
  int64_t v_wide = ((int64_t)v_big * (int64_t)2LL);
  {
    int64_t ni_e4 = v_wide;
    printf("%lld\n", (long long)(ni_e4));
  }
  double v_f = 1.5;
  v_f = ((v_f * 2.0) + 0.25);
  {
    double ni_e5 = v_f;
    printf("%g\n", ni_e5);
  }
  float v_g32 = 0.5f;
  v_g32 = (v_g32 + 0.25f);
  {
    double ni_e6 = v_g32;
    printf("%g\n", ni_e6);
  }
  double v_inf = (1.0 / 0.0);
  {
    double ni_e7 = v_inf;
    printf("%g\n", ni_e7);
  }
  double v_nan = (0.0 / 0.0);
  {
    int64_t ni_e8 = ni_ftoi(v_nan);
    printf("%lld\n", (long long)(ni_e8));
  }
  double v_short = 2.9;
  {
    int64_t ni_e9 = ni_ftoi(v_short);
    printf("%lld\n", (long long)(ni_e9));
  }
  {
    double ni_e10 = (((double)(7LL)) / 2.0);
    printf("%g\n", ni_e10);
  }
  return NULL;
}

int main(void) {
  pthread_t ni_threads[1];
  if (pthread_create(&ni_threads[0], NULL, t_main, NULL) != 0) { fprintf(stderr, "nifty: failed to start thread main\n"); return 1; }
  pthread_join(ni_threads[0], NULL);
  return 0;
}
