// Generated by nifty from tests/scripts/locks.nifty. Do not edit.
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <pthread.h>

static pthread_mutex_t g_talk = PTHREAD_MUTEX_INITIALIZER;
static pthread_mutex_t g_data = PTHREAD_MUTEX_INITIALIZER;
static int64_t g_ready;
static int64_t g_value;

static void *t_producer(void *ni_arg) {
  (void)ni_arg;
  pthread_mutex_lock(&g_talk);
  {
    printf("sending\n");
    pthread_mutex_lock(&g_data);
    {
      g_value = 42LL;
      g_ready = 1LL;
    }
    pthread_mutex_unlock(&g_data);
  }
  pthread_mutex_unlock(&g_talk);
  return NULL;
}

static void *t_consumer(void *ni_arg) {
  (void)ni_arg;
  bool v_done = false;
  {
    int64_t ni_trips0 = 0;
    while (ni_trips0 < 1000000000LL && (!v_done)) {
      pthread_mutex_lock(&g_data);
      {
        if (g_ready == 1LL) {
          v_done = true;
        }
      }
      pthread_mutex_unlock(&g_data);
      ++ni_trips0;
    }
  }
  pthread_mutex_lock(&g_talk);
  {
    pthread_mutex_lock(&g_data);
    {
      {
        int64_t ni_e1 = g_value;
        printf("%lld\n", (long long)(ni_e1));
      }
    }
    pthread_mutex_unlock(&g_data);
  }
  pthread_mutex_unlock(&g_talk);
  return NULL;
}

int main(void) {
  pthread_t ni_threads[2];
  if (pthread_create(&ni_threads[0], NULL, t_producer, NULL) != 0) { fprintf(stderr, "nifty: failed to start thread producer\n"); return 1; }
  if (pthread_create(&ni_threads[1], NULL, t_consumer, NULL) != 0) { fprintf(stderr, "nifty: failed to start thread consumer\n"); return 1; }
  pthread_join(ni_threads[0], NULL);
  pthread_join(ni_threads[1], NULL);
  return 0;
}
