// Generated by nifty from tests/scripts/text.nifty. Do not edit.
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <pthread.h>

// The one float -> int conversion: saturating, NaN-safe (NaN -> 0).
// A bare C cast of an out-of-range or NaN value is undefined behavior,
// so nifty never emits one.
static inline int64_t ni_ftoi(double f) {
  if (f != f) return 0;
  if (f >= 9223372036854775807.0) return INT64_MAX;
  if (f <= -9223372036854775808.0) return INT64_MIN;
  return (int64_t)f;
}

typedef struct {
  int64_t m_val;
  bool m_ok;
} NS_pi;
static int64_t NS_pi_or(NS_pi r, int64_t fb) { return r.m_ok ? r.m_val : fb; }

typedef struct {
  int64_t m_len;
  uint8_t m_data[20];
} NS_s20;
static void NS_s20_adds(NS_s20 *s, const uint8_t *d, int64_t k) { memcpy(&s->m_data[s->m_len], d, (size_t)k); s->m_len += k; }
static void NS_s20_clear(NS_s20 *s) { s->m_len = 0; }
static void NS_s20_setLen(NS_s20 *s, int64_t k) { s->m_len = k; }
static void NS_s20_addByte(NS_s20 *s, int64_t b) { s->m_data[s->m_len] = (uint8_t)b; s->m_len += 1; }
static void NS_s20_addNum(NS_s20 *s, int64_t v) {
  char t[24]; int k = snprintf(t, sizeof t, "%lld", (long long)v);
  if (k < 0) k = 0; if (k > 20) k = 20;
  memcpy(&s->m_data[s->m_len], t, (size_t)k); s->m_len += k;
}
static bool NS_s20_startsWith(const NS_s20 *s, const uint8_t *d, int64_t k) {
  if (k > s->m_len) return false;
  return memcmp(s->m_data, d, (size_t)k) == 0;
}
static bool NS_s20_endsWith(const NS_s20 *s, const uint8_t *d, int64_t k) {
  if (k > s->m_len) return false;
  return memcmp(&s->m_data[s->m_len - k], d, (size_t)k) == 0;
}
static int64_t NS_s20_findRaw(const NS_s20 *s, const uint8_t *d, int64_t k) {
  if (k == 0) return 0;
  if (k > s->m_len) return -1;
  for (int64_t i = 0; i + k <= s->m_len; ++i)
    if (memcmp(&s->m_data[i], d, (size_t)k) == 0) return i;
  return -1;
}
static bool NS_s20_contains(const NS_s20 *s, const uint8_t *d, int64_t k) { return NS_s20_findRaw(s, d, k) >= 0; }
static int64_t NS_s20_findByteRaw(const NS_s20 *s, int64_t b) {
  for (int64_t i = 0; i < s->m_len; ++i)
    if (s->m_data[i] == (uint8_t)b) return i;
  return -1;
}
static void NS_s20_copyRange(NS_s20 *s, const uint8_t *d, int64_t dlen, int64_t lo, int64_t hi) {
  // Total by clamping: any bounds give a defined result.
  if (lo < 0) lo = 0;
  if (hi > dlen) hi = dlen;
  int64_t k = hi - lo;
  if (k < 0) k = 0;
  if (k > 20LL) k = 20LL;
  memcpy(s->m_data, &d[lo], (size_t)k); s->m_len = k;
}
static bool NS_s20_toIntRaw(const NS_s20 *s, int64_t *out) {
  int64_t i = 0, sign = 1, v = 0;
  if (s->m_len == 0) return false;
  if (s->m_data[0] == (uint8_t)45) { sign = -1; i = 1; }
  if (i >= s->m_len) return false;
  for (; i < s->m_len; ++i) {
    uint8_t c = s->m_data[i];
    if (c < 48 || c > 57) return false;
    if (v > 922337203685477580LL) return false;
    v = v * 10 + (c - 48);
    if (v < 0) return false;
  }
  *out = sign * v; return true;
}
static NS_pi NS_s20_find(const NS_s20 *s, const uint8_t *d, int64_t k) {
  int64_t r = NS_s20_findRaw(s, d, k);
  NS_pi o = {0}; if (r >= 0) { o.m_val = r; o.m_ok = true; }
  return o;
}
static NS_pi NS_s20_findByte(const NS_s20 *s, int64_t b) {
  int64_t r = NS_s20_findByteRaw(s, b);
  NS_pi o = {0}; if (r >= 0) { o.m_val = r; o.m_ok = true; }
  return o;
}
static NS_pi NS_s20_toInt(const NS_s20 *s) {
  int64_t v = 0;
  NS_pi o = {0};
  if (NS_s20_toIntRaw(s, &v)) { o.m_val = v; o.m_ok = true; }
  return o;
}

typedef struct {
  int64_t m_len;
  NS_s20 m_data[8];
} NS_q8_s20;
static void NS_q8_s20_add(NS_q8_s20 *s, NS_s20 v) { s->m_data[s->m_len] = v; s->m_len += 1; }
static bool NS_q8_s20_push(NS_q8_s20 *s, NS_s20 v) { if (s->m_len >= 8LL) return false; s->m_data[s->m_len] = v; s->m_len += 1; return true; }
static NS_s20 NS_q8_s20_pop(NS_q8_s20 *s) { s->m_len -= 1; return s->m_data[s->m_len]; }
static void NS_q8_s20_clear(NS_q8_s20 *s) { s->m_len = 0; }
static void NS_q8_s20_setLen(NS_q8_s20 *s, int64_t k) { s->m_len = k; }
static void NS_q8_s20_addByte(NS_q8_s20 *s, int64_t b) { s->m_data[s->m_len] = (uint8_t)b; s->m_len += 1; }
static void NS_q8_s20_addNum(NS_q8_s20 *s, int64_t v) {
  char t[24]; int k = snprintf(t, sizeof t, "%lld", (long long)v);
  if (k < 0) k = 0; if (k > 20) k = 20;
  memcpy(&s->m_data[s->m_len], t, (size_t)k); s->m_len += k;
}
static bool NS_q8_s20_startsWith(const NS_q8_s20 *s, const uint8_t *d, int64_t k) {
  if (k > s->m_len) return false;
  return memcmp(s->m_data, d, (size_t)k) == 0;
}
static bool NS_q8_s20_endsWith(const NS_q8_s20 *s, const uint8_t *d, int64_t k) {
  if (k > s->m_len) return false;
  return memcmp(&s->m_data[s->m_len - k], d, (size_t)k) == 0;
}
static int64_t NS_q8_s20_findRaw(const NS_q8_s20 *s, const uint8_t *d, int64_t k) {
  if (k == 0) return 0;
  if (k > s->m_len) return -1;
  for (int64_t i = 0; i + k <= s->m_len; ++i)
    if (memcmp(&s->m_data[i], d, (size_t)k) == 0) return i;
  return -1;
}
static bool NS_q8_s20_contains(const NS_q8_s20 *s, const uint8_t *d, int64_t k) { return NS_q8_s20_findRaw(s, d, k) >= 0; }
static int64_t NS_q8_s20_findByteRaw(const NS_q8_s20 *s, int64_t b) {
  for (int64_t i = 0; i < s->m_len; ++i)
    if (s->m_data[i] == (uint8_t)b) return i;
  return -1;
}
static void NS_q8_s20_copyRange(NS_q8_s20 *s, const uint8_t *d, int64_t dlen, int64_t lo, int64_t hi) {
  // Total by clamping: any bounds give a defined result.
  if (lo < 0) lo = 0;
  if (hi > dlen) hi = dlen;
  int64_t k = hi - lo;
  if (k < 0) k = 0;
  if (k > 8LL) k = 8LL;
  memcpy(s->m_data, &d[lo], (size_t)k); s->m_len = k;
}
static bool NS_q8_s20_toIntRaw(const NS_q8_s20 *s, int64_t *out) {
  int64_t i = 0, sign = 1, v = 0;
  if (s->m_len == 0) return false;
  if (s->m_data[0] == (uint8_t)45) { sign = -1; i = 1; }
  if (i >= s->m_len) return false;
  for (; i < s->m_len; ++i) {
    uint8_t c = s->m_data[i];
    if (c < 48 || c > 57) return false;
    if (v > 922337203685477580LL) return false;
    v = v * 10 + (c - 48);
    if (v < 0) return false;
  }
  *out = sign * v; return true;
}
static NS_pi NS_q8_s20_find(const NS_q8_s20 *s, const uint8_t *d, int64_t k) {
  int64_t r = NS_q8_s20_findRaw(s, d, k);
  NS_pi o = {0}; if (r >= 0) { o.m_val = r; o.m_ok = true; }
  return o;
}
static NS_pi NS_q8_s20_findByte(const NS_q8_s20 *s, int64_t b) {
  int64_t r = NS_q8_s20_findByteRaw(s, b);
  NS_pi o = {0}; if (r >= 0) { o.m_val = r; o.m_ok = true; }
  return o;
}
static NS_pi NS_q8_s20_toInt(const NS_q8_s20 *s) {
  int64_t v = 0;
  NS_pi o = {0};
  if (NS_q8_s20_toIntRaw(s, &v)) { o.m_val = v; o.m_ok = true; }
  return o;
}

typedef struct {
  int64_t m_len;
  uint8_t m_data[40];
} NS_s40;
static void NS_s40_adds(NS_s40 *s, const uint8_t *d, int64_t k) { memcpy(&s->m_data[s->m_len], d, (size_t)k); s->m_len += k; }
static void NS_s40_clear(NS_s40 *s) { s->m_len = 0; }
static void NS_s40_setLen(NS_s40 *s, int64_t k) { s->m_len = k; }
static void NS_s40_addByte(NS_s40 *s, int64_t b) { s->m_data[s->m_len] = (uint8_t)b; s->m_len += 1; }
static void NS_s40_addNum(NS_s40 *s, int64_t v) {
  char t[24]; int k = snprintf(t, sizeof t, "%lld", (long long)v);
  if (k < 0) k = 0; if (k > 20) k = 20;
  memcpy(&s->m_data[s->m_len], t, (size_t)k); s->m_len += k;
}
static bool NS_s40_startsWith(const NS_s40 *s, const uint8_t *d, int64_t k) {
  if (k > s->m_len) return false;
  return memcmp(s->m_data, d, (size_t)k) == 0;
}
static bool NS_s40_endsWith(const NS_s40 *s, const uint8_t *d, int64_t k) {
  if (k > s->m_len) return false;
  return memcmp(&s->m_data[s->m_len - k], d, (size_t)k) == 0;
}
static int64_t NS_s40_findRaw(const NS_s40 *s, const uint8_t *d, int64_t k) {
  if (k == 0) return 0;
  if (k > s->m_len) return -1;
  for (int64_t i = 0; i + k <= s->m_len; ++i)
    if (memcmp(&s->m_data[i], d, (size_t)k) == 0) return i;
  return -1;
}
static bool NS_s40_contains(const NS_s40 *s, const uint8_t *d, int64_t k) { return NS_s40_findRaw(s, d, k) >= 0; }
static int64_t NS_s40_findByteRaw(const NS_s40 *s, int64_t b) {
  for (int64_t i = 0; i < s->m_len; ++i)
    if (s->m_data[i] == (uint8_t)b) return i;
  return -1;
}
static void NS_s40_copyRange(NS_s40 *s, const uint8_t *d, int64_t dlen, int64_t lo, int64_t hi) {
  // Total by clamping: any bounds give a defined result.
  if (lo < 0) lo = 0;
  if (hi > dlen) hi = dlen;
  int64_t k = hi - lo;
  if (k < 0) k = 0;
  if (k > 40LL) k = 40LL;
  memcpy(s->m_data, &d[lo], (size_t)k); s->m_len = k;
}
static bool NS_s40_toIntRaw(const NS_s40 *s, int64_t *out) {
  int64_t i = 0, sign = 1, v = 0;
  if (s->m_len == 0) return false;
  if (s->m_data[0] == (uint8_t)45) { sign = -1; i = 1; }
  if (i >= s->m_len) return false;
  for (; i < s->m_len; ++i) {
    uint8_t c = s->m_data[i];
    if (c < 48 || c > 57) return false;
    if (v > 922337203685477580LL) return false;
    v = v * 10 + (c - 48);
    if (v < 0) return false;
  }
  *out = sign * v; return true;
}
static NS_pi NS_s40_find(const NS_s40 *s, const uint8_t *d, int64_t k) {
  int64_t r = NS_s40_findRaw(s, d, k);
  NS_pi o = {0}; if (r >= 0) { o.m_val = r; o.m_ok = true; }
  return o;
}
static NS_pi NS_s40_findByte(const NS_s40 *s, int64_t b) {
  int64_t r = NS_s40_findByteRaw(s, b);
  NS_pi o = {0}; if (r >= 0) { o.m_val = r; o.m_ok = true; }
  return o;
}
static NS_pi NS_s40_toInt(const NS_s40 *s) {
  int64_t v = 0;
  NS_pi o = {0};
  if (NS_s40_toIntRaw(s, &v)) { o.m_val = v; o.m_ok = true; }
  return o;
}

typedef struct {
  int64_t m_len;
  int64_t m_data[4];
} NS_q4_i;
static void NS_q4_i_add(NS_q4_i *s, int64_t v) { s->m_data[s->m_len] = v; s->m_len += 1; }
static bool NS_q4_i_push(NS_q4_i *s, int64_t v) { if (s->m_len >= 4LL) return false; s->m_data[s->m_len] = v; s->m_len += 1; return true; }
static int64_t NS_q4_i_pop(NS_q4_i *s) { s->m_len -= 1; return s->m_data[s->m_len]; }
static void NS_q4_i_clear(NS_q4_i *s) { s->m_len = 0; }
static void NS_q4_i_setLen(NS_q4_i *s, int64_t k) { s->m_len = k; }
static void NS_q4_i_addByte(NS_q4_i *s, int64_t b) { s->m_data[s->m_len] = (uint8_t)b; s->m_len += 1; }
static void NS_q4_i_addNum(NS_q4_i *s, int64_t v) {
  char t[24]; int k = snprintf(t, sizeof t, "%lld", (long long)v);
  if (k < 0) k = 0; if (k > 20) k = 20;
  memcpy(&s->m_data[s->m_len], t, (size_t)k); s->m_len += k;
}
static bool NS_q4_i_startsWith(const NS_q4_i *s, const uint8_t *d, int64_t k) {
  if (k > s->m_len) return false;
  return memcmp(s->m_data, d, (size_t)k) == 0;
}
static bool NS_q4_i_endsWith(const NS_q4_i *s, const uint8_t *d, int64_t k) {
  if (k > s->m_len) return false;
  return memcmp(&s->m_data[s->m_len - k], d, (size_t)k) == 0;
}
static int64_t NS_q4_i_findRaw(const NS_q4_i *s, const uint8_t *d, int64_t k) {
  if (k == 0) return 0;
  if (k > s->m_len) return -1;
  for (int64_t i = 0; i + k <= s->m_len; ++i)
    if (memcmp(&s->m_data[i], d, (size_t)k) == 0) return i;
  return -1;
}
static bool NS_q4_i_contains(const NS_q4_i *s, const uint8_t *d, int64_t k) { return NS_q4_i_findRaw(s, d, k) >= 0; }
static int64_t NS_q4_i_findByteRaw(const NS_q4_i *s, int64_t b) {
  for (int64_t i = 0; i < s->m_len; ++i)
    if (s->m_data[i] == (uint8_t)b) return i;
  return -1;
}
static void NS_q4_i_copyRange(NS_q4_i *s, const uint8_t *d, int64_t dlen, int64_t lo, int64_t hi) {
  // Total by clamping: any bounds give a defined result.
  if (lo < 0) lo = 0;
  if (hi > dlen) hi = dlen;
  int64_t k = hi - lo;
  if (k < 0) k = 0;
  if (k > 4LL) k = 4LL;
  memcpy(s->m_data, &d[lo], (size_t)k); s->m_len = k;
}
static bool NS_q4_i_toIntRaw(const NS_q4_i *s, int64_t *out) {
  int64_t i = 0, sign = 1, v = 0;
  if (s->m_len == 0) return false;
  if (s->m_data[0] == (uint8_t)45) { sign = -1; i = 1; }
  if (i >= s->m_len) return false;
  for (; i < s->m_len; ++i) {
    uint8_t c = s->m_data[i];
    if (c < 48 || c > 57) return false;
    if (v > 922337203685477580LL) return false;
    v = v * 10 + (c - 48);
    if (v < 0) return false;
  }
  *out = sign * v; return true;
}
static NS_pi NS_q4_i_find(const NS_q4_i *s, const uint8_t *d, int64_t k) {
  int64_t r = NS_q4_i_findRaw(s, d, k);
  NS_pi o = {0}; if (r >= 0) { o.m_val = r; o.m_ok = true; }
  return o;
}
static NS_pi NS_q4_i_findByte(const NS_q4_i *s, int64_t b) {
  int64_t r = NS_q4_i_findByteRaw(s, b);
  NS_pi o = {0}; if (r >= 0) { o.m_val = r; o.m_ok = true; }
  return o;
}
static NS_pi NS_q4_i_toInt(const NS_q4_i *s) {
  int64_t v = 0;
  NS_pi o = {0};
  if (NS_q4_i_toIntRaw(s, &v)) { o.m_val = v; o.m_ok = true; }
  return o;
}

static const int64_t C_MaxWords = 8LL;

static NS_q8_s20 g_words;

static void f_collect(void) {
  if ((int64_t)g_words.m_len < (int64_t)C_MaxWords) {
    NS_q8_s20_add(&g_words, (NS_s20){ .m_len = 5LL, .m_data = "nifty" });
  }
  if ((int64_t)g_words.m_len < (int64_t)C_MaxWords) {
    NS_q8_s20_add(&g_words, (NS_s20){ .m_len = 6LL, .m_data = "proves" });
  }
  if ((int64_t)g_words.m_len < (int64_t)C_MaxWords) {
    NS_q8_s20_add(&g_words, (NS_s20){ .m_len = 7LL, .m_data = "bounded" });
  }
}

static int64_t f_score(NS_s20 p_s) {
  int64_t v_total = 0LL;
  {
    NS_s20 *ni_it0 = &p_s;
    const int64_t ni_n0 = ni_it0->m_len;
    for (int64_t ni_ix0 = 0; ni_ix0 < ni_n0; ++ni_ix0) {
      int64_t v_b = ni_it0->m_data[ni_ix0];
      v_total = ((int64_t)v_total + (int64_t)v_b);
    }
  }
  return v_total;
}

static void *t_main(void *ni_arg) {
  (void)ni_arg;
  NS_s40 v_greeting = (NS_s40){ .m_len = 5LL, .m_data = "hello" };
  NS_s40_adds(&v_greeting, (const uint8_t *)", ", 2LL);
  NS_s40_adds(&v_greeting, (const uint8_t *)"world", 5LL);
  {
    NS_s40 ni_e1 = v_greeting;
    printf("%.*s\n", (int)(ni_e1.m_len), (const char *)ni_e1.m_data);
  }
  {
    int64_t ni_e2 = v_greeting.m_len;
    printf("%lld\n", (long long)(ni_e2));
  }
  f_collect();
  {
    int64_t ni_e3 = g_words.m_len;
    printf("%lld\n", (long long)(ni_e3));
  }
  {
    NS_q8_s20 *ni_it4 = &g_words;
    const int64_t ni_n4 = ni_it4->m_len;
    for (int64_t ni_ix4 = 0; ni_ix4 < ni_n4; ++ni_ix4) {
      NS_s20 v_w = ni_it4->m_data[ni_ix4];
      {
        NS_s20 ni_e5 = v_w;
        int64_t ni_e6 = f_score(v_w);
        printf("%.*s -> %lld\n", (int)(ni_e5.m_len), (const char *)ni_e5.m_data, (long long)(ni_e6));
      }
    }
  }
  NS_q4_i v_nums = {0};
  int64_t v_i = 0LL;
  while ((int64_t)v_i < (int64_t)6LL) {
    int64_t ni_t7 = v_i;
    bool ni_t8 = NS_q4_i_push(&v_nums, ((int64_t)ni_t7 * (int64_t)10LL));
    if (ni_t8) {
      {
        int64_t ni_e9 = ((int64_t)v_i * (int64_t)10LL);
        printf("pushed %lld\n", (long long)(ni_e9));
      }
    } else {
      {
        int64_t ni_e10 = ((int64_t)v_i * (int64_t)10LL);
        printf("full at %lld\n", (long long)(ni_e10));
      }
    }
    v_i = ((int64_t)v_i + (int64_t)1LL);
  }
  if ((int64_t)v_nums.m_len > (int64_t)2LL) {
    {
      int64_t ni_e11 = v_nums.m_data[0LL];
      int64_t ni_e12 = v_nums.m_data[2LL];
      printf("%lld %lld\n", (long long)(ni_e11), (long long)(ni_e12));
    }
  }
  return NULL;
}

int main(void) {
  pthread_t ni_threads[1];
  if (pthread_create(&ni_threads[0], NULL, t_main, NULL) != 0) { fprintf(stderr, "nifty: failed to start thread main\n"); return 1; }
  pthread_join(ni_threads[0], NULL);
  return 0;
}
